---
- name: Import postgresql rpm gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL

- name: Install postgresql repository
  ansible.builtin.package:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

